### ISSUE TITLE
User.user.permissiom

### ISSUE THREAD

**Issue by shubhamnag007** [mfogel/django-simple-email-confirmation#57]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0000021DA49B3A60>
Traceback (most recent call last):
  File "C:\Users\nEW u\PycharmProjects\prayrollproj3\venv\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\nEW u\PycharmProjects\prayrollproj3\venv\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\nEW u\PycharmProjects\prayrollproj3\venv\lib\site-packages\django\core\management\base.py", line 425, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
auth.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
auth.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.
paymentapp.User.groups: (fields.E304) Reverse accessor for 'User.groups' clashes with reverse accessor for 'User.groups'.
	HINT: Add or change a related_name argument to the definition for 'User.groups' or 'User.groups'.
paymentapp.User.user_permissions: (fields.E304) Reverse accessor for 'User.user_permissions' clashes with reverse accessor for 'User.user_permissions'.
	HINT: Add or change a related_name argument to the definition for 'User.user_permissions' or 'User.user_permissions'.

**Comment by ferndot** [comment]
Hey @shubhamnag007. Can you please paste your user model here?

**Comment by Nieto2018** [comment]
Hello,

I leave a link, it can help.

https://github.com/mfogel/django-simple-email-confirmation/issues/65#issuecomment-561205683
